### ISSUE TITLE
Attemped out of bounds Tuple access

### ISSUE THREAD

**Issue by Herdinger** [ptal/oak#69]
When I compile following grammar I get an out of bounds error for define_to_directive:
http://pastebin.com/HpihTNDF

The generated code shows that it tries to access element 2 and 3 of the tuple although the type signature has only two elements.

**Comment by ptal** [comment]
Hello! First of all, thank you for trying out my library, I'm really happy I got a user ;-)

Could you add the code referenced by the following use-statements please?

```rust
use super::Directive;
use super::IfElse;
```

Also you can write an identifier with the rule `identifier = !["0-9"] ["a-zA-Z0-9_"]*`, therefore you can use `stringify` and remove `stringify2`.
