### ISSUE TITLE
Generalized string literals (bytes and raw sequences)

### ISSUE THREAD

**Issue by ptal** [ptal/oak#91]
Accepts string literal of the form `b"xxx"` and `r##"\n\tblabla"##` as described in the [rust reference](https://doc.rust-lang.org/reference.html#character-literals).

**Comment by zyvitski** [comment]
I was just about to open another issue on this subject when unnoticed this. It would be great to be able to have a built in way of matching rustlike string, or at least expressing escape sequences so that we can construct our own.

**Comment by ptal** [comment]
Yes, it would be cool! I'm wondering if we need to modify something else than the parser.

**Comment by ptal** [comment]
Triage: string literals are now automatically supported (thanks to the parser using `syn`).
